README.md
Not sure if this is a good idea but I would have loved some minimal information on getting started.
=> add some minimal quickstart notes

static/js/jquery.dataTables.plugin.ipaddress.js, templates/network/ipaddress_list.html
Pulled ip-address plugin from datatables.net.
Also, shouldn't datatable() be enabled on all tables per default ?
=> feature: flip on dataTable.js in ip list

Lagerregal/settings_template.py, Lagerregal/urls.py, devices/ajax.py, static/css/main.css, templates/devices/device_detail.html, templates/devices/puppetsoftware.html
loads software fact from puppetdb with ajax when configured
=> puppet: add software tab in device details

templates/devices/puppetdetails.html
merge after puppet software tab
=> enhancement: sort puppet details table

Lagerregal/settings_template.py, Lagerregal/urls.py, dependencies.txt, templates/base.html, templates/login.html, users/views.py
+ drop patterns()
+ changed string view parameters to references
+ changed reverse url names in templates
+ contex_processors module path
+ current_app should now be attached to request
+ defer reversion update
=> Changes for Django 1.10

devicegroups/tests.py, devices/tests.py, devices/views.py, devicetags/tests.py, devicetypes/tests.py, locations/tests.py, mail/tests.py, main/tests.py, network/tests.py, users/tests.py
=> Test branch

devices/forms.py
tiny change --> ordered possible email recipients by group name / last name
=> sorted Emailrecipients

devices/tests.py, devices/views.py
Dear testers,
are you okay with granularity/naming? Also, is this logical to you?
Fixes #170
=> Fix: set returndate on device trashing

devices/models.py, devices/views.py, templates/base.html
The detail view have now a container, breadcrumbs and a footer.
Do we want to have these buttons in the breadcrumbs?
=> Fixed detail view of public devices

devices/admin.py, templates/users/profile.html, users/views.py
Added lending history to user page (device-tab)
=> added lending history to profile of user

Lagerregal/settings_template.py, Lagerregal/utils.py, api/views.py, devicegroups/views.py, devices/ajax.py, devices/forms.py, devices/management/commands/ldapimport.py, devices/templatetags/devicetags.py, devices/views.py, devicetypes/forms.py, devicetypes/views.py, history/views.py, locations/views.py, main/ajax.py, network/views.py, users/forms.py, users/models.py, users/tests.py, users/views.py
=> fixed unicode bug

templates/mail/mailtemplate_list.html
=> added department column for mailtemplate

templates/devices/device_detail.html
=> added id info

devices/forms.py
=> order devicetypes in select by device count

devices/views.py
In #265 I had accidentally removed the ability to search for IP adresses.
=> allow to search by ip address

templates/devices/device_detail.html, templates/devices/device_lend.html, templates/network/ipaddress_detail.html, templates/users/department_detail.html, users/templatetags/usertags.py
=> replace django-permission templatetag

.gitignore, README.md, locale/de/LC_MESSAGES/django.po
It turns out the german translation isn't all that incomplete. It's just that it is not compiled automatically. I think we should add a simple install script sometime.
Anyway, I updated the translations and added a note to README.
=> update german translations

dependencies.txt
=> update django to 2.0

static/js/lagerregal.js, templates/devices/device_detail.html
Works around the fix for [CVE-2019-8331](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-8331)
=> Fix popover

devices/forms.py
=> use select2 for emailrecipients in device mail modal

templates/base.html
Don't really know why this is broken. May be related to dee43cd.
=> fix noty theme

network/tests.py, network/views.py, users/tests.py, users/views.py
I did the next best thing without too much in-depth analysis.
=> Fix some tests
